#!/usr/bin/env bash
# PreToolUse hook: block writes to /context.
#
# context/ is regenerated wholesale by scripts/ha-context-dump.sh every 6
# hours (and on demand via input_button.ha_context_dump_now). Any manual
# edit is overwritten on the next snapshot, so direct writes are always a
# bug — the upstream source in HA must be fixed instead.
#
# Catches:
#   - Edit / Write / MultiEdit / NotebookEdit with tool_input.file_path
#     resolving inside ${CLAUDE_PROJECT_DIR}/context/
#   - Bash commands with common write patterns targeting context/:
#       rm/mv/cp/tee/truncate/install/chmod/chown/dd/touch/mkdir/rmdir/ln
#       sed -i ... context/...
#       > context/...  /  >> context/...  (anywhere in the command line)
#       git restore|checkout|reset|clean|rm|mv ... context/...
#
# Limitations: by design only a best-effort guardrail. A determined caller
# can still bypass via `cd context && rm ...`, python file writes, etc.
# The goal is to make accidental clobbers fail loudly.

set -euo pipefail

payload=$(cat)
tool=$(jq -r '.tool_name // ""' <<<"$payload")

block() {
    {
        printf 'blocked: /context is regenerated by scripts/ha-context-dump.sh.\n'
        printf '         manual edits will be overwritten on the next snapshot.\n'
        printf '         fix the upstream source in HA, then refresh via\n'
        printf '         input_button.ha_context_dump_now. see CLAUDE.md\n'
        printf '         section "HA Runtime State Context".\n'
        printf '         offending %s: %s\n' "$1" "$2"
    } >&2
    exit 2
}

case "$tool" in
    Edit|Write|MultiEdit|NotebookEdit)
        path=$(jq -r '.tool_input.file_path // .tool_input.notebook_path // ""' <<<"$payload")
        [[ -z "$path" ]] && exit 0
        project_root=${CLAUDE_PROJECT_DIR:-$PWD}
        # context/README.md is reference documentation, not generated state —
        # the dump only writes the *.json / *.yaml artifacts it explicitly
        # produces. Allow edits so the file map can be kept current.
        in_context=$(python3 - "$project_root" "$path" <<'PY'
import os
import sys

root, path = sys.argv[1], sys.argv[2]
abs_path = path if os.path.isabs(path) else os.path.join(root, path)
abs_path = os.path.normpath(abs_path)
ctx = os.path.normpath(os.path.join(root, "context"))
readme = os.path.join(ctx, "README.md")
if abs_path == readme:
    print("no")
elif abs_path == ctx or abs_path.startswith(ctx + os.sep):
    print("yes")
else:
    print("no")
PY
        )
        [[ "$in_context" == "yes" ]] && block "path" "$path"
        ;;
    Bash)
        cmd=$(jq -r '.tool_input.command // ""' <<<"$payload")
        # Fast path: no mention of context anywhere → not our problem.
        [[ "$cmd" != *context* ]] && exit 0

        if grep -qE '(^|[[:space:];&|`(])(rm|mv|cp|tee|truncate|install|chmod|chown|dd|touch|mkdir|rmdir|ln)[[:space:]]+([^|;&]*[[:space:]])?context/' <<<"$cmd" \
            || grep -qE 'sed[[:space:]]+[^|;&]*-i[^|;&]*[[:space:]]context/' <<<"$cmd" \
            || grep -qE '>{1,2}[[:space:]]*"?'\''?context/' <<<"$cmd" \
            || grep -qE 'git[[:space:]]+(restore|checkout|reset|clean|rm|mv)[^|;&]*[[:space:]]context(/|$|[[:space:]])' <<<"$cmd"; then
            block "command" "$cmd"
        fi
        ;;
esac

exit 0
