# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

# Includes
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Cloud config
cloud:

# Alarm panel
alarm_control_panel:
  - platform: manual
    name: Home Alarm
    code: !secret alarm_code
    arming_time: 30
    delay_time: 20
    trigger_time: 4
    disarmed:
      trigger_time: 0
    armed_home:
      arming_time: 0
      delay_time: 0

cover:
  - platform: myq
    username: cpitzi@gmail.com
    password: !secret myq_password

# Nest
nest:
  client_id: 214160765048-sp1o3nhgn3b98nn7fe745tdcd8dl0pog.apps.googleusercontent.com
  client_secret: !secret nest_client_secret
  # "Project ID" in the Device Access Console
  project_id: 7d8d7b5a-7e58-47bb-a9aa-2035aff06349
  # Provide the full path exactly as shown under "Subscription name" in Google Cloud Console
  subscriber_id: projects/burnished-city-258420/subscriptions/mdhome

# Google wifi
sensor:
  - platform: google_wifi
